### ISSUE TITLE
Revisar arquitectura de tareas

### ISSUE THREAD

**Issue by abenassi** [datosgobar/django-datajsonar#62]
**Contexto**

Actualmente es difícil administrar el croneo e implementación de tareas, o conjuntos de tareas, teniendo en cuenta todas las potenciales necesidades síncronas / asíncronas de ejecución, tanto croneadas como manuales.

`django-datajsonar` es un buen lugar donde resolver genéricamente cómo facilitar el desarrollo de estas tareas, para las aplicaciones que lo tienen como dependencia (`series-tiempo-ar-api` y `monitoreo-apertura`).

**Propuesta**

Investigar y ejecutar opciones de implementación   de las tareas (y de su disponibilización vía interfaz de Django) teniendo en cuenta:

+ necesidades del *usuario administrador de la aplicación final*
+ necesidades del *usuario desarrollador de una aplicación con la dependencia `django-datajsonar`*

siempre que parezca una solución generalizable desde `django-datajsonar`:

+ [x] Como "usuario administrador" quiero levantar la aplicación sin tener que configurarla inicialmente, en lo posible. *La aplicación debería ya venir con una configuración default inicial de sus tareas*
+ [x] Como "usuario administrador" quiero poder disparar manualmente cada una de las tareas disponibles en mi aplicación desde la UI.
+ [ ] Como "usuario desarrollador de una aplicación con `django-datajsonar como dependencia" quiero generar tareas y conjuntos encadenados de tareas, que a veces se disparan asincrónicamente y que a veces se encadenan sincrónicamente, y donde a veces la falla de una tarea implica el aborto de la siguiente, mientras que otras continúa más allá del resultado de la tarea anterior.
+ [ ] Como "usuario administrador" quiero poder cronear cualquier tarea o conjunto de tareas disponibles en mi aplicación, especificando hora y días de la semana en la que se ejecuta (gralmente para evitar o no su ejecución en fines de semana).
